version: "3.3"

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: node_mosquitto_container
    restart: unless-stopped
    network_mode: "host"

  mqtt:
    build:
      context: ./mqtt  
    image: node_mqtt_image 
    container_name: node_mqtt_container
    restart: unless-stopped
    network_mode: "host"

  ros2:
    build:
      context: ./ros2_rust  
    image: node_ros2_image 
    container_name: node_ros2_container
    restart: unless-stopped
    network_mode: "host"

  actix:
    build:
      context: ./actix  
    image: node_actix_image 
    container_name: node_actix_container
    restart: unless-stopped
    network_mode: "host"
    