version: "3.3"

services:
  actix:
    build:
      context: ./actix  
    image: node_actix_image 
    container_name: node_actix_container
    restart: unless-stopped
    network_mode: "host"

  websocket:
    build:
      context: ./websocket  
    image: node_websocket_image 
    container_name: node_websocket_container
    restart: unless-stopped
    network_mode: "host"

  tcp:
    build:
      context: ./tcp  
    image: node_tcp_image 
    container_name: node_tcp_container
    restart: unless-stopped
    network_mode: "host"

  sm_cpp:
    build:
      context: ./sm_cpp  
    image: node_sm_cpp_image 
    shm_size: '256m'
    container_name: node_sm_cpp_container
    restart: unless-stopped
    network_mode: "host"
  
  sm_rust:
    build:
      context: ./sm_rust  
    image: node_sm_rust_image 
    shm_size: '256m'
    container_name: node_sm_rust_container
    restart: unless-stopped
    network_mode: "host"
    
  mqtt:
    build:
      context: ./mqtt  
    image: node_mqtt_image 
    container_name: node_mqtt_container
    restart: unless-stopped
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: node_mosquitto_container
    restart: unless-stopped
    network_mode: "host"
  

  
    