version: "3.3"

services:
  tcp:
    image: lp02781/node_tcp_image 
    container_name: node_tcp_container
    restart: unless-stopped
    network_mode: "host"

  sm_cpp:  
    image: lp02781/node_sm_cpp_image 
    shm_size: '256m'
    container_name: node_sm_cpp_container
    restart: unless-stopped
    network_mode: "host"
  
  sm_rust:
    image: lp02781/node_sm_rust_image 
    shm_size: '256m'
    container_name: node_sm_rust_container
    restart: unless-stopped
    network_mode: "host"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: node_mosquitto_container
    restart: unless-stopped
    network_mode: "host"

  mqtt:
    image: lp02781/node_mqtt_image
    container_name: node_mqtt_container
    restart: unless-stopped
    network_mode: "host"
  
  ros2:
    image: lp02781/node_ros2_image
    container_name: node_ros2_container
    restart: unless-stopped  
    network_mode: "host" 

  actix:
    image: lp02781/node_actix_image
    container_name: node_actix_container
    restart: unless-stopped  
    network_mode: "host" 
    