[supervisord]
nodaemon=true

[program:json_rpc_1]
command=python /opt/json_rpc_1.py
autostart=true
autorestart=true

[program:json_rpc_2]
command=python /opt/json_rpc_2.py
autostart=true
autorestart=true