name: Actix CI/CD pipeline

on:
  pull_request:
    branches:
      - main 
    paths:
      - 'actix/**' 

  push:
    branches:
      - main 
    paths:
      - 'actix/**' 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build the project
        run: |
          cd ./actix
          cargo build --release

      - name: Run tests
        run: |
          cd ./actix
          cargo test

  deploy_docker:
    needs: build 
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t node_actix_image:latest ./actix

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag node_actix_image:latest lp02781/node_actix_image:latest
          docker push lp02781/node_actix_image:latest

      - name: Deploy to production
        run: |
          echo "Deploying the Docker image to production Docker Hub"
