name: Interface CI/CD pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'interface/**'

  push:
    branches:
      - main
    paths:
      - 'interface/**'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd interface
          npm ci

      - name: Build React App
        run: |
          cd interface
          npm run build

  deploy_docker:
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t node_interface_image:latest ./interface

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag node_interface_image:latest lp02781/node_interface_image:latest
          docker push lp02781/node_interface_image:latest

      - name: Deploy to production
        run: |
          echo "Deployed interface image to Docker Hub"
