name: ROS2 Node CI/CD pipeline

on:
  pull_request:
    branches:
      - main
    paths:
      - 'ros2_rust/**' 
  
  push:
    branches:
      - main
    paths:
      - 'ros2_rust/**' 

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t node_ros2_image:latest ./ros2_rust

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker image
        run: |
          docker tag node_ros2_image:latest lp02781/node_ros2_image:latest 

      - name: Push Docker image to Docker Hub
        run: |
          docker push lp02781/node_ros2_image:latest  

      - name: Deploy to production
        run: |
          echo "Deploying the Docker image to production Docker Hub"
